name: EKS Terraform CI/CD

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - '**'  

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          
      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true
        
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        
      - name: Upload Plan Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: tfplan
          
      - name: Comment PR with Plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            try {
              const planOutput = execSync('terraform show -no-color tfplan', { encoding: 'utf8' });
              const comment = `## EKS Terraform Plan
              
              <details>
              <summary>Show Plan</summary>
              
              \`\`\`
              ${planOutput}
              \`\`\`
              
              </details>`;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            } catch (error) {
              console.error('Failed to generate plan comment:', error);
            }
            
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        
      - name: Capture Important Outputs
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "## EKS Deployment Complete! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Cluster Information" >> $GITHUB_STEP_SUMMARY
          echo "**Cluster Name:** \`$(terraform output -raw cluster_name)\`" >> $GITHUB_STEP_SUMMARY
          echo "**Cluster Endpoint:** \`$(terraform output -raw cluster_endpoint)\`" >> $GITHUB_STEP_SUMMARY
          echo "**Region:** \`$(terraform output -raw region)\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### 🔑 Important for Tasky Deployment" >> $GITHUB_STEP_SUMMARY
          echo "**Secrets Manager Role ARN:**" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$(terraform output -raw eks_secrets_manager_role_arn)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. **Configure kubectl:**" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "aws eks update-kubeconfig --name $(terraform output -raw cluster_name)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "2. **Update service-account.yaml in Tasky repo with the Role ARN above**" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "3. **Deploy Tasky application**" >> $GITHUB_STEP_SUMMARY
          
      - name: Save Outputs for Later Use
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          mkdir -p outputs
          terraform output -json > outputs/terraform-outputs.json
          echo "CLUSTER_NAME=$(terraform output -raw cluster_name)" >> outputs/cluster-info.env
          echo "ROLE_ARN=$(terraform output -raw eks_secrets_manager_role_arn)" >> outputs/cluster-info.env
          echo "CLUSTER_ENDPOINT=$(terraform output -raw cluster_endpoint)" >> outputs/cluster-info.env
          echo "VPC_PEERING_ID=$(terraform output -raw vpc_peering_connection_id)" >> outputs/cluster-info.env
          
      - name: Upload Deployment Outputs
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: eks-deployment-outputs
          path: outputs/
          retention-days: 30
