name: EKS Terraform CI/CD

on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - '**'  

# Required for OIDC
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::442042553076:role/github-actions-eks-role
          aws-region: us-east-1
          audience: sts.amazonaws.com
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest
          
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        
      - name: Capture Important Outputs
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "## EKS Deployment Complete! 🎉" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Cluster Information" >> $GITHUB_STEP_SUMMARY
          echo "**Cluster Name:** $(terraform output -raw cluster_name)" >> $GITHUB_STEP_SUMMARY
          echo "**Region:** $(terraform output -raw region)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Role ARN for service-account.yaml:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$(terraform output -raw eks_secrets_manager_role_arn)" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
